name: PlanningApp
options:
  bundleIdPrefix: com.remi2.planning
targets:
  PlanningApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: PlanningApp
    info:
      properties:
        UILaunchScreen: {}
        CFBundleDevelopmentRegion: fr
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    settings:
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGN_IDENTITY: ""
      PROVISIONING_PROFILE_SPECIFIER: ""
      DEVELOPMENT_TEAM: ""
